server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://aegis_loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: aegis_backend
    static_configs:
    - targets:
        - localhost
      labels:
        job: aegis_backend
        __path__: /mnt/logs/backend.log
